name: flightdelay
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - pandas
    - numpy
    - seaborn
    - joblib
    - azureml-core
    - scikit-learn==0.23.2
    - mlflow
    - azureml-defaults
    - azureml-dataset-runtime
    - azureml-mlflow