command: python train.py --data {{inputs.weather}}
code:
  local_path: .
environment: 
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: conda.yaml
inputs:
  weather: flightdelayweather_ds_clean
compute: cpu-cluster
