command: python train.py --data {{inputs.weather}}
code:
  local_path: .
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:8
inputs:
  weather: flightdelayweather_ds_clean
compute: cpu-cluster
